export { default as Home } from "./Home/Home";
export { default as Products } from "./Products/Products";
export { default as ProductPage } from "./Products/ProductDetail";
export { default as StoreLocation } from "./StoreLocation";
export { default as Contact } from "./Contact";
export { default as Wishlist } from "./Wishlist";
export { default as CartPage } from "./CartPage";
export { default as Login } from "./Auth/Login";
export { default as Register } from "./Auth/Register";
export { default as Checkout } from "./Checkout";
export { default as Ordered } from "./Ordered";
// export { default as ErrorPage } from "./ErrorPage";
